// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GomeplusRpcServices.proto

package com.gomeplus.grpc.protobuf;

public final class GomeplusRpcServices {
  private GomeplusRpcServices() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReqBatchGroupIdInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.gomeplus.grpc.protobuf.ReqBatchGroupIdInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string groupId = 1;</code>
     */
    java.lang.String getGroupId();
    /**
     * <code>optional string groupId = 1;</code>
     */
    com.google.protobuf.ByteString
        getGroupIdBytes();

    /**
     * <pre>
     *上一次拉取群成员的时间戳
     * </pre>
     *
     * <code>optional int64 lastPullTimestamp = 2;</code>
     */
    long getLastPullTimestamp();

    /**
     * <pre>
     * 0-查询新加入和离开的群成员，1-新加入的成员，2-删除的新成员 默认为 0 
     * </pre>
     *
     * <code>optional int32 status = 3;</code>
     */
    int getStatus();

    /**
     * <pre>
     *用户ID
     * </pre>
     *
     * <code>optional int64 userId = 4;</code>
     */
    long getUserId();

    /**
     * <pre>
     *用户ID集合
     * </pre>
     *
     * <code>repeated int64 userIds = 5;</code>
     */
    java.util.List<java.lang.Long> getUserIdsList();
    /**
     * <pre>
     *用户ID集合
     * </pre>
     *
     * <code>repeated int64 userIds = 5;</code>
     */
    int getUserIdsCount();
    /**
     * <pre>
     *用户ID集合
     * </pre>
     *
     * <code>repeated int64 userIds = 5;</code>
     */
    long getUserIds(int index);

    /**
     * <pre>
     *分页页数
     * </pre>
     *
     * <code>optional int32 page = 6;</code>
     */
    int getPage();

    /**
     * <pre>
     *分页大小
     * </pre>
     *
     * <code>optional int32 pageSize = 7;</code>
     */
    int getPageSize();
  }
  /**
   * <pre>
   *注：公共参数
   *	一、请求参数：
   *	1.traceId(long)-日志跟踪和调用者缓存使用
   *	2.extra(string)-扩展信息(可以为空)
   *	3.appId(string)-区分不同应用 （redis操作不需要）
   *	二、返回参数：
   *	1.traceId(long)-日志跟踪和调用者缓存使用
   *	2.extra(string)-扩展信息(可能为空)
   *	3.success(bool)-调用是否成功
   *批量拉取群成员的群信息
   * </pre>
   *
   * Protobuf type {@code com.gomeplus.grpc.protobuf.ReqBatchGroupIdInfo}
   */
  public  static final class ReqBatchGroupIdInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.gomeplus.grpc.protobuf.ReqBatchGroupIdInfo)
      ReqBatchGroupIdInfoOrBuilder {
    // Use ReqBatchGroupIdInfo.newBuilder() to construct.
    private ReqBatchGroupIdInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReqBatchGroupIdInfo() {
      groupId_ = "";
      lastPullTimestamp_ = 0L;
      status_ = 0;
      userId_ = 0L;
      userIds_ = java.util.Collections.emptyList();
      page_ = 0;
      pageSize_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ReqBatchGroupIdInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              groupId_ = s;
              break;
            }
            case 16: {

              lastPullTimestamp_ = input.readInt64();
              break;
            }
            case 24: {

              status_ = input.readInt32();
              break;
            }
            case 32: {

              userId_ = input.readInt64();
              break;
            }
            case 40: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                userIds_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000010;
              }
              userIds_.add(input.readInt64());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
                userIds_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000010;
              }
              while (input.getBytesUntilLimit() > 0) {
                userIds_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 48: {

              page_ = input.readInt32();
              break;
            }
            case 56: {

              pageSize_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          userIds_ = java.util.Collections.unmodifiableList(userIds_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gomeplus.grpc.protobuf.GomeplusRpcServices.internal_static_com_gomeplus_grpc_protobuf_ReqBatchGroupIdInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gomeplus.grpc.protobuf.GomeplusRpcServices.internal_static_com_gomeplus_grpc_protobuf_ReqBatchGroupIdInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo.class, com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo.Builder.class);
    }

    private int bitField0_;
    public static final int GROUPID_FIELD_NUMBER = 1;
    private volatile java.lang.Object groupId_;
    /**
     * <code>optional string groupId = 1;</code>
     */
    public java.lang.String getGroupId() {
      java.lang.Object ref = groupId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groupId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string groupId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGroupIdBytes() {
      java.lang.Object ref = groupId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTPULLTIMESTAMP_FIELD_NUMBER = 2;
    private long lastPullTimestamp_;
    /**
     * <pre>
     *上一次拉取群成员的时间戳
     * </pre>
     *
     * <code>optional int64 lastPullTimestamp = 2;</code>
     */
    public long getLastPullTimestamp() {
      return lastPullTimestamp_;
    }

    public static final int STATUS_FIELD_NUMBER = 3;
    private int status_;
    /**
     * <pre>
     * 0-查询新加入和离开的群成员，1-新加入的成员，2-删除的新成员 默认为 0 
     * </pre>
     *
     * <code>optional int32 status = 3;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int USERID_FIELD_NUMBER = 4;
    private long userId_;
    /**
     * <pre>
     *用户ID
     * </pre>
     *
     * <code>optional int64 userId = 4;</code>
     */
    public long getUserId() {
      return userId_;
    }

    public static final int USERIDS_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Long> userIds_;
    /**
     * <pre>
     *用户ID集合
     * </pre>
     *
     * <code>repeated int64 userIds = 5;</code>
     */
    public java.util.List<java.lang.Long>
        getUserIdsList() {
      return userIds_;
    }
    /**
     * <pre>
     *用户ID集合
     * </pre>
     *
     * <code>repeated int64 userIds = 5;</code>
     */
    public int getUserIdsCount() {
      return userIds_.size();
    }
    /**
     * <pre>
     *用户ID集合
     * </pre>
     *
     * <code>repeated int64 userIds = 5;</code>
     */
    public long getUserIds(int index) {
      return userIds_.get(index);
    }
    private int userIdsMemoizedSerializedSize = -1;

    public static final int PAGE_FIELD_NUMBER = 6;
    private int page_;
    /**
     * <pre>
     *分页页数
     * </pre>
     *
     * <code>optional int32 page = 6;</code>
     */
    public int getPage() {
      return page_;
    }

    public static final int PAGESIZE_FIELD_NUMBER = 7;
    private int pageSize_;
    /**
     * <pre>
     *分页大小
     * </pre>
     *
     * <code>optional int32 pageSize = 7;</code>
     */
    public int getPageSize() {
      return pageSize_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!getGroupIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, groupId_);
      }
      if (lastPullTimestamp_ != 0L) {
        output.writeInt64(2, lastPullTimestamp_);
      }
      if (status_ != 0) {
        output.writeInt32(3, status_);
      }
      if (userId_ != 0L) {
        output.writeInt64(4, userId_);
      }
      if (getUserIdsList().size() > 0) {
        output.writeUInt32NoTag(42);
        output.writeUInt32NoTag(userIdsMemoizedSerializedSize);
      }
      for (int i = 0; i < userIds_.size(); i++) {
        output.writeInt64NoTag(userIds_.get(i));
      }
      if (page_ != 0) {
        output.writeInt32(6, page_);
      }
      if (pageSize_ != 0) {
        output.writeInt32(7, pageSize_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getGroupIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, groupId_);
      }
      if (lastPullTimestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, lastPullTimestamp_);
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, status_);
      }
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, userId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < userIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(userIds_.get(i));
        }
        size += dataSize;
        if (!getUserIdsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        userIdsMemoizedSerializedSize = dataSize;
      }
      if (page_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, page_);
      }
      if (pageSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, pageSize_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo)) {
        return super.equals(obj);
      }
      com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo other = (com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo) obj;

      boolean result = true;
      result = result && getGroupId()
          .equals(other.getGroupId());
      result = result && (getLastPullTimestamp()
          == other.getLastPullTimestamp());
      result = result && (getStatus()
          == other.getStatus());
      result = result && (getUserId()
          == other.getUserId());
      result = result && getUserIdsList()
          .equals(other.getUserIdsList());
      result = result && (getPage()
          == other.getPage());
      result = result && (getPageSize()
          == other.getPageSize());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + GROUPID_FIELD_NUMBER;
      hash = (53 * hash) + getGroupId().hashCode();
      hash = (37 * hash) + LASTPULLTIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastPullTimestamp());
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      if (getUserIdsCount() > 0) {
        hash = (37 * hash) + USERIDS_FIELD_NUMBER;
        hash = (53 * hash) + getUserIdsList().hashCode();
      }
      hash = (37 * hash) + PAGE_FIELD_NUMBER;
      hash = (53 * hash) + getPage();
      hash = (37 * hash) + PAGESIZE_FIELD_NUMBER;
      hash = (53 * hash) + getPageSize();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *注：公共参数
     *	一、请求参数：
     *	1.traceId(long)-日志跟踪和调用者缓存使用
     *	2.extra(string)-扩展信息(可以为空)
     *	3.appId(string)-区分不同应用 （redis操作不需要）
     *	二、返回参数：
     *	1.traceId(long)-日志跟踪和调用者缓存使用
     *	2.extra(string)-扩展信息(可能为空)
     *	3.success(bool)-调用是否成功
     *批量拉取群成员的群信息
     * </pre>
     *
     * Protobuf type {@code com.gomeplus.grpc.protobuf.ReqBatchGroupIdInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.gomeplus.grpc.protobuf.ReqBatchGroupIdInfo)
        com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gomeplus.grpc.protobuf.GomeplusRpcServices.internal_static_com_gomeplus_grpc_protobuf_ReqBatchGroupIdInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gomeplus.grpc.protobuf.GomeplusRpcServices.internal_static_com_gomeplus_grpc_protobuf_ReqBatchGroupIdInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo.class, com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo.Builder.class);
      }

      // Construct using com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        groupId_ = "";

        lastPullTimestamp_ = 0L;

        status_ = 0;

        userId_ = 0L;

        userIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        page_ = 0;

        pageSize_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gomeplus.grpc.protobuf.GomeplusRpcServices.internal_static_com_gomeplus_grpc_protobuf_ReqBatchGroupIdInfo_descriptor;
      }

      public com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo getDefaultInstanceForType() {
        return com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo.getDefaultInstance();
      }

      public com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo build() {
        com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo buildPartial() {
        com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo result = new com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.groupId_ = groupId_;
        result.lastPullTimestamp_ = lastPullTimestamp_;
        result.status_ = status_;
        result.userId_ = userId_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          userIds_ = java.util.Collections.unmodifiableList(userIds_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.userIds_ = userIds_;
        result.page_ = page_;
        result.pageSize_ = pageSize_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo) {
          return mergeFrom((com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo other) {
        if (other == com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo.getDefaultInstance()) return this;
        if (!other.getGroupId().isEmpty()) {
          groupId_ = other.groupId_;
          onChanged();
        }
        if (other.getLastPullTimestamp() != 0L) {
          setLastPullTimestamp(other.getLastPullTimestamp());
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (!other.userIds_.isEmpty()) {
          if (userIds_.isEmpty()) {
            userIds_ = other.userIds_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureUserIdsIsMutable();
            userIds_.addAll(other.userIds_);
          }
          onChanged();
        }
        if (other.getPage() != 0) {
          setPage(other.getPage());
        }
        if (other.getPageSize() != 0) {
          setPageSize(other.getPageSize());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object groupId_ = "";
      /**
       * <code>optional string groupId = 1;</code>
       */
      public java.lang.String getGroupId() {
        java.lang.Object ref = groupId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          groupId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string groupId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGroupIdBytes() {
        java.lang.Object ref = groupId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          groupId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string groupId = 1;</code>
       */
      public Builder setGroupId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string groupId = 1;</code>
       */
      public Builder clearGroupId() {
        
        groupId_ = getDefaultInstance().getGroupId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string groupId = 1;</code>
       */
      public Builder setGroupIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        groupId_ = value;
        onChanged();
        return this;
      }

      private long lastPullTimestamp_ ;
      /**
       * <pre>
       *上一次拉取群成员的时间戳
       * </pre>
       *
       * <code>optional int64 lastPullTimestamp = 2;</code>
       */
      public long getLastPullTimestamp() {
        return lastPullTimestamp_;
      }
      /**
       * <pre>
       *上一次拉取群成员的时间戳
       * </pre>
       *
       * <code>optional int64 lastPullTimestamp = 2;</code>
       */
      public Builder setLastPullTimestamp(long value) {
        
        lastPullTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *上一次拉取群成员的时间戳
       * </pre>
       *
       * <code>optional int64 lastPullTimestamp = 2;</code>
       */
      public Builder clearLastPullTimestamp() {
        
        lastPullTimestamp_ = 0L;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <pre>
       * 0-查询新加入和离开的群成员，1-新加入的成员，2-删除的新成员 默认为 0 
       * </pre>
       *
       * <code>optional int32 status = 3;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <pre>
       * 0-查询新加入和离开的群成员，1-新加入的成员，2-删除的新成员 默认为 0 
       * </pre>
       *
       * <code>optional int32 status = 3;</code>
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 0-查询新加入和离开的群成员，1-新加入的成员，2-删除的新成员 默认为 0 
       * </pre>
       *
       * <code>optional int32 status = 3;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private long userId_ ;
      /**
       * <pre>
       *用户ID
       * </pre>
       *
       * <code>optional int64 userId = 4;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <pre>
       *用户ID
       * </pre>
       *
       * <code>optional int64 userId = 4;</code>
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户ID
       * </pre>
       *
       * <code>optional int64 userId = 4;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Long> userIds_ = java.util.Collections.emptyList();
      private void ensureUserIdsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          userIds_ = new java.util.ArrayList<java.lang.Long>(userIds_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <pre>
       *用户ID集合
       * </pre>
       *
       * <code>repeated int64 userIds = 5;</code>
       */
      public java.util.List<java.lang.Long>
          getUserIdsList() {
        return java.util.Collections.unmodifiableList(userIds_);
      }
      /**
       * <pre>
       *用户ID集合
       * </pre>
       *
       * <code>repeated int64 userIds = 5;</code>
       */
      public int getUserIdsCount() {
        return userIds_.size();
      }
      /**
       * <pre>
       *用户ID集合
       * </pre>
       *
       * <code>repeated int64 userIds = 5;</code>
       */
      public long getUserIds(int index) {
        return userIds_.get(index);
      }
      /**
       * <pre>
       *用户ID集合
       * </pre>
       *
       * <code>repeated int64 userIds = 5;</code>
       */
      public Builder setUserIds(
          int index, long value) {
        ensureUserIdsIsMutable();
        userIds_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户ID集合
       * </pre>
       *
       * <code>repeated int64 userIds = 5;</code>
       */
      public Builder addUserIds(long value) {
        ensureUserIdsIsMutable();
        userIds_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户ID集合
       * </pre>
       *
       * <code>repeated int64 userIds = 5;</code>
       */
      public Builder addAllUserIds(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureUserIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, userIds_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户ID集合
       * </pre>
       *
       * <code>repeated int64 userIds = 5;</code>
       */
      public Builder clearUserIds() {
        userIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      private int page_ ;
      /**
       * <pre>
       *分页页数
       * </pre>
       *
       * <code>optional int32 page = 6;</code>
       */
      public int getPage() {
        return page_;
      }
      /**
       * <pre>
       *分页页数
       * </pre>
       *
       * <code>optional int32 page = 6;</code>
       */
      public Builder setPage(int value) {
        
        page_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *分页页数
       * </pre>
       *
       * <code>optional int32 page = 6;</code>
       */
      public Builder clearPage() {
        
        page_ = 0;
        onChanged();
        return this;
      }

      private int pageSize_ ;
      /**
       * <pre>
       *分页大小
       * </pre>
       *
       * <code>optional int32 pageSize = 7;</code>
       */
      public int getPageSize() {
        return pageSize_;
      }
      /**
       * <pre>
       *分页大小
       * </pre>
       *
       * <code>optional int32 pageSize = 7;</code>
       */
      public Builder setPageSize(int value) {
        
        pageSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *分页大小
       * </pre>
       *
       * <code>optional int32 pageSize = 7;</code>
       */
      public Builder clearPageSize() {
        
        pageSize_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.gomeplus.grpc.protobuf.ReqBatchGroupIdInfo)
    }

    // @@protoc_insertion_point(class_scope:com.gomeplus.grpc.protobuf.ReqBatchGroupIdInfo)
    private static final com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo();
    }

    public static com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReqBatchGroupIdInfo>
        PARSER = new com.google.protobuf.AbstractParser<ReqBatchGroupIdInfo>() {
      public ReqBatchGroupIdInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ReqBatchGroupIdInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReqBatchGroupIdInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReqBatchGroupIdInfo> getParserForType() {
      return PARSER;
    }

    public com.gomeplus.grpc.protobuf.GomeplusRpcServices.ReqBatchGroupIdInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gomeplus_grpc_protobuf_ReqBatchGroupIdInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gomeplus_grpc_protobuf_ReqBatchGroupIdInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031GomeplusRpcServices.proto\022\032com.gomeplu" +
      "s.grpc.protobuf\"\222\001\n\023ReqBatchGroupIdInfo\022" +
      "\017\n\007groupId\030\001 \001(\t\022\031\n\021lastPullTimestamp\030\002 " +
      "\001(\003\022\016\n\006status\030\003 \001(\005\022\016\n\006userId\030\004 \001(\003\022\017\n\007u" +
      "serIds\030\005 \003(\003\022\014\n\004page\030\006 \001(\005\022\020\n\010pageSize\030\007" +
      " \001(\005B\002P\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_gomeplus_grpc_protobuf_ReqBatchGroupIdInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_gomeplus_grpc_protobuf_ReqBatchGroupIdInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gomeplus_grpc_protobuf_ReqBatchGroupIdInfo_descriptor,
        new java.lang.String[] { "GroupId", "LastPullTimestamp", "Status", "UserId", "UserIds", "Page", "PageSize", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
