// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserRpcServices.proto

package com.gomeplus.grpc.protobuf;

public final class UserRpcServices {
  private UserRpcServices() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestUserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.gomeplus.grpc.protobuf.RequestUser)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string appId = 1;</code>
     */
    java.lang.String getAppId();
    /**
     * <code>optional string appId = 1;</code>
     */
    com.google.protobuf.ByteString
        getAppIdBytes();

    /**
     * <code>optional int64 userId = 2;</code>
     */
    long getUserId();

    /**
     * <code>optional string token = 3;</code>
     */
    java.lang.String getToken();
    /**
     * <code>optional string token = 3;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <pre>
     *记录ID
     * </pre>
     *
     * <code>optional int64 traceId = 4;</code>
     */
    long getTraceId();

    /**
     * <pre>
     *用于扩展信息
     * </pre>
     *
     * <code>optional string extra = 5;</code>
     */
    java.lang.String getExtra();
    /**
     * <pre>
     *用于扩展信息
     * </pre>
     *
     * <code>optional string extra = 5;</code>
     */
    com.google.protobuf.ByteString
        getExtraBytes();

    /**
     * <pre>
     *客户端类型
     * </pre>
     *
     * <code>optional int32 clientType = 6;</code>
     */
    int getClientType();

    /**
     * <code>optional string groupId = 7;</code>
     */
    java.lang.String getGroupId();
    /**
     * <code>optional string groupId = 7;</code>
     */
    com.google.protobuf.ByteString
        getGroupIdBytes();

    /**
     * <code>optional int32 manufacture = 8;</code>
     */
    int getManufacture();
  }
  /**
   * Protobuf type {@code com.gomeplus.grpc.protobuf.RequestUser}
   */
  public  static final class RequestUser extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.gomeplus.grpc.protobuf.RequestUser)
      RequestUserOrBuilder {
    // Use RequestUser.newBuilder() to construct.
    private RequestUser(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestUser() {
      appId_ = "";
      userId_ = 0L;
      token_ = "";
      traceId_ = 0L;
      extra_ = "";
      clientType_ = 0;
      groupId_ = "";
      manufacture_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RequestUser(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              appId_ = s;
              break;
            }
            case 16: {

              userId_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            case 32: {

              traceId_ = input.readInt64();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              extra_ = s;
              break;
            }
            case 48: {

              clientType_ = input.readInt32();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              groupId_ = s;
              break;
            }
            case 64: {

              manufacture_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gomeplus.grpc.protobuf.UserRpcServices.internal_static_com_gomeplus_grpc_protobuf_RequestUser_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gomeplus.grpc.protobuf.UserRpcServices.internal_static_com_gomeplus_grpc_protobuf_RequestUser_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser.class, com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser.Builder.class);
    }

    public static final int APPID_FIELD_NUMBER = 1;
    private volatile java.lang.Object appId_;
    /**
     * <code>optional string appId = 1;</code>
     */
    public java.lang.String getAppId() {
      java.lang.Object ref = appId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string appId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAppIdBytes() {
      java.lang.Object ref = appId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private long userId_;
    /**
     * <code>optional int64 userId = 2;</code>
     */
    public long getUserId() {
      return userId_;
    }

    public static final int TOKEN_FIELD_NUMBER = 3;
    private volatile java.lang.Object token_;
    /**
     * <code>optional string token = 3;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>optional string token = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRACEID_FIELD_NUMBER = 4;
    private long traceId_;
    /**
     * <pre>
     *记录ID
     * </pre>
     *
     * <code>optional int64 traceId = 4;</code>
     */
    public long getTraceId() {
      return traceId_;
    }

    public static final int EXTRA_FIELD_NUMBER = 5;
    private volatile java.lang.Object extra_;
    /**
     * <pre>
     *用于扩展信息
     * </pre>
     *
     * <code>optional string extra = 5;</code>
     */
    public java.lang.String getExtra() {
      java.lang.Object ref = extra_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        extra_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用于扩展信息
     * </pre>
     *
     * <code>optional string extra = 5;</code>
     */
    public com.google.protobuf.ByteString
        getExtraBytes() {
      java.lang.Object ref = extra_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extra_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTTYPE_FIELD_NUMBER = 6;
    private int clientType_;
    /**
     * <pre>
     *客户端类型
     * </pre>
     *
     * <code>optional int32 clientType = 6;</code>
     */
    public int getClientType() {
      return clientType_;
    }

    public static final int GROUPID_FIELD_NUMBER = 7;
    private volatile java.lang.Object groupId_;
    /**
     * <code>optional string groupId = 7;</code>
     */
    public java.lang.String getGroupId() {
      java.lang.Object ref = groupId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groupId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string groupId = 7;</code>
     */
    public com.google.protobuf.ByteString
        getGroupIdBytes() {
      java.lang.Object ref = groupId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MANUFACTURE_FIELD_NUMBER = 8;
    private int manufacture_;
    /**
     * <code>optional int32 manufacture = 8;</code>
     */
    public int getManufacture() {
      return manufacture_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAppIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, appId_);
      }
      if (userId_ != 0L) {
        output.writeInt64(2, userId_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, token_);
      }
      if (traceId_ != 0L) {
        output.writeInt64(4, traceId_);
      }
      if (!getExtraBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, extra_);
      }
      if (clientType_ != 0) {
        output.writeInt32(6, clientType_);
      }
      if (!getGroupIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, groupId_);
      }
      if (manufacture_ != 0) {
        output.writeInt32(8, manufacture_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAppIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, appId_);
      }
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, userId_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, token_);
      }
      if (traceId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, traceId_);
      }
      if (!getExtraBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, extra_);
      }
      if (clientType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, clientType_);
      }
      if (!getGroupIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, groupId_);
      }
      if (manufacture_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, manufacture_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser)) {
        return super.equals(obj);
      }
      com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser other = (com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser) obj;

      boolean result = true;
      result = result && getAppId()
          .equals(other.getAppId());
      result = result && (getUserId()
          == other.getUserId());
      result = result && getToken()
          .equals(other.getToken());
      result = result && (getTraceId()
          == other.getTraceId());
      result = result && getExtra()
          .equals(other.getExtra());
      result = result && (getClientType()
          == other.getClientType());
      result = result && getGroupId()
          .equals(other.getGroupId());
      result = result && (getManufacture()
          == other.getManufacture());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + APPID_FIELD_NUMBER;
      hash = (53 * hash) + getAppId().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + TRACEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTraceId());
      hash = (37 * hash) + EXTRA_FIELD_NUMBER;
      hash = (53 * hash) + getExtra().hashCode();
      hash = (37 * hash) + CLIENTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getClientType();
      hash = (37 * hash) + GROUPID_FIELD_NUMBER;
      hash = (53 * hash) + getGroupId().hashCode();
      hash = (37 * hash) + MANUFACTURE_FIELD_NUMBER;
      hash = (53 * hash) + getManufacture();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.gomeplus.grpc.protobuf.RequestUser}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.gomeplus.grpc.protobuf.RequestUser)
        com.gomeplus.grpc.protobuf.UserRpcServices.RequestUserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gomeplus.grpc.protobuf.UserRpcServices.internal_static_com_gomeplus_grpc_protobuf_RequestUser_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gomeplus.grpc.protobuf.UserRpcServices.internal_static_com_gomeplus_grpc_protobuf_RequestUser_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser.class, com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser.Builder.class);
      }

      // Construct using com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        appId_ = "";

        userId_ = 0L;

        token_ = "";

        traceId_ = 0L;

        extra_ = "";

        clientType_ = 0;

        groupId_ = "";

        manufacture_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gomeplus.grpc.protobuf.UserRpcServices.internal_static_com_gomeplus_grpc_protobuf_RequestUser_descriptor;
      }

      public com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser getDefaultInstanceForType() {
        return com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser.getDefaultInstance();
      }

      public com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser build() {
        com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser buildPartial() {
        com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser result = new com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser(this);
        result.appId_ = appId_;
        result.userId_ = userId_;
        result.token_ = token_;
        result.traceId_ = traceId_;
        result.extra_ = extra_;
        result.clientType_ = clientType_;
        result.groupId_ = groupId_;
        result.manufacture_ = manufacture_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser) {
          return mergeFrom((com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser other) {
        if (other == com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser.getDefaultInstance()) return this;
        if (!other.getAppId().isEmpty()) {
          appId_ = other.appId_;
          onChanged();
        }
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (other.getTraceId() != 0L) {
          setTraceId(other.getTraceId());
        }
        if (!other.getExtra().isEmpty()) {
          extra_ = other.extra_;
          onChanged();
        }
        if (other.getClientType() != 0) {
          setClientType(other.getClientType());
        }
        if (!other.getGroupId().isEmpty()) {
          groupId_ = other.groupId_;
          onChanged();
        }
        if (other.getManufacture() != 0) {
          setManufacture(other.getManufacture());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object appId_ = "";
      /**
       * <code>optional string appId = 1;</code>
       */
      public java.lang.String getAppId() {
        java.lang.Object ref = appId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string appId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAppIdBytes() {
        java.lang.Object ref = appId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string appId = 1;</code>
       */
      public Builder setAppId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string appId = 1;</code>
       */
      public Builder clearAppId() {
        
        appId_ = getDefaultInstance().getAppId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string appId = 1;</code>
       */
      public Builder setAppIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appId_ = value;
        onChanged();
        return this;
      }

      private long userId_ ;
      /**
       * <code>optional int64 userId = 2;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>optional int64 userId = 2;</code>
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 userId = 2;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>optional string token = 3;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string token = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string token = 3;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 3;</code>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 3;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }

      private long traceId_ ;
      /**
       * <pre>
       *记录ID
       * </pre>
       *
       * <code>optional int64 traceId = 4;</code>
       */
      public long getTraceId() {
        return traceId_;
      }
      /**
       * <pre>
       *记录ID
       * </pre>
       *
       * <code>optional int64 traceId = 4;</code>
       */
      public Builder setTraceId(long value) {
        
        traceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *记录ID
       * </pre>
       *
       * <code>optional int64 traceId = 4;</code>
       */
      public Builder clearTraceId() {
        
        traceId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object extra_ = "";
      /**
       * <pre>
       *用于扩展信息
       * </pre>
       *
       * <code>optional string extra = 5;</code>
       */
      public java.lang.String getExtra() {
        java.lang.Object ref = extra_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          extra_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用于扩展信息
       * </pre>
       *
       * <code>optional string extra = 5;</code>
       */
      public com.google.protobuf.ByteString
          getExtraBytes() {
        java.lang.Object ref = extra_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          extra_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用于扩展信息
       * </pre>
       *
       * <code>optional string extra = 5;</code>
       */
      public Builder setExtra(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        extra_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用于扩展信息
       * </pre>
       *
       * <code>optional string extra = 5;</code>
       */
      public Builder clearExtra() {
        
        extra_ = getDefaultInstance().getExtra();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用于扩展信息
       * </pre>
       *
       * <code>optional string extra = 5;</code>
       */
      public Builder setExtraBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        extra_ = value;
        onChanged();
        return this;
      }

      private int clientType_ ;
      /**
       * <pre>
       *客户端类型
       * </pre>
       *
       * <code>optional int32 clientType = 6;</code>
       */
      public int getClientType() {
        return clientType_;
      }
      /**
       * <pre>
       *客户端类型
       * </pre>
       *
       * <code>optional int32 clientType = 6;</code>
       */
      public Builder setClientType(int value) {
        
        clientType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户端类型
       * </pre>
       *
       * <code>optional int32 clientType = 6;</code>
       */
      public Builder clearClientType() {
        
        clientType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object groupId_ = "";
      /**
       * <code>optional string groupId = 7;</code>
       */
      public java.lang.String getGroupId() {
        java.lang.Object ref = groupId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          groupId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string groupId = 7;</code>
       */
      public com.google.protobuf.ByteString
          getGroupIdBytes() {
        java.lang.Object ref = groupId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          groupId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string groupId = 7;</code>
       */
      public Builder setGroupId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string groupId = 7;</code>
       */
      public Builder clearGroupId() {
        
        groupId_ = getDefaultInstance().getGroupId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string groupId = 7;</code>
       */
      public Builder setGroupIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        groupId_ = value;
        onChanged();
        return this;
      }

      private int manufacture_ ;
      /**
       * <code>optional int32 manufacture = 8;</code>
       */
      public int getManufacture() {
        return manufacture_;
      }
      /**
       * <code>optional int32 manufacture = 8;</code>
       */
      public Builder setManufacture(int value) {
        
        manufacture_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 manufacture = 8;</code>
       */
      public Builder clearManufacture() {
        
        manufacture_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.gomeplus.grpc.protobuf.RequestUser)
    }

    // @@protoc_insertion_point(class_scope:com.gomeplus.grpc.protobuf.RequestUser)
    private static final com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser();
    }

    public static com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestUser>
        PARSER = new com.google.protobuf.AbstractParser<RequestUser>() {
      public RequestUser parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RequestUser(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestUser> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestUser> getParserForType() {
      return PARSER;
    }

    public com.gomeplus.grpc.protobuf.UserRpcServices.RequestUser getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseUserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.gomeplus.grpc.protobuf.ResponseUser)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool success = 1;</code>
     */
    boolean getSuccess();

    /**
     * <code>optional string token = 2;</code>
     */
    java.lang.String getToken();
    /**
     * <code>optional string token = 2;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <pre>
     *用户token时候有效
     * </pre>
     *
     * <code>optional bool isVaild = 3;</code>
     */
    boolean getIsVaild();

    /**
     * <pre>
     *记录ID
     * </pre>
     *
     * <code>optional int64 traceId = 4;</code>
     */
    long getTraceId();

    /**
     * <pre>
     *用于扩展信息
     * </pre>
     *
     * <code>optional string extra = 5;</code>
     */
    java.lang.String getExtra();
    /**
     * <pre>
     *用于扩展信息
     * </pre>
     *
     * <code>optional string extra = 5;</code>
     */
    com.google.protobuf.ByteString
        getExtraBytes();

    /**
     * <pre>
     *是否开启消息免打扰
     * </pre>
     *
     * <code>optional bool isMsgBlocked = 6;</code>
     */
    boolean getIsMsgBlocked();

    /**
     * <pre>
     *push计数
     * </pre>
     *
     * <code>optional int64 pushCount = 7;</code>
     */
    long getPushCount();
  }
  /**
   * Protobuf type {@code com.gomeplus.grpc.protobuf.ResponseUser}
   */
  public  static final class ResponseUser extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.gomeplus.grpc.protobuf.ResponseUser)
      ResponseUserOrBuilder {
    // Use ResponseUser.newBuilder() to construct.
    private ResponseUser(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseUser() {
      success_ = false;
      token_ = "";
      isVaild_ = false;
      traceId_ = 0L;
      extra_ = "";
      isMsgBlocked_ = false;
      pushCount_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ResponseUser(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              success_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            case 24: {

              isVaild_ = input.readBool();
              break;
            }
            case 32: {

              traceId_ = input.readInt64();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              extra_ = s;
              break;
            }
            case 48: {

              isMsgBlocked_ = input.readBool();
              break;
            }
            case 56: {

              pushCount_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gomeplus.grpc.protobuf.UserRpcServices.internal_static_com_gomeplus_grpc_protobuf_ResponseUser_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gomeplus.grpc.protobuf.UserRpcServices.internal_static_com_gomeplus_grpc_protobuf_ResponseUser_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser.class, com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>optional bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    public static final int TOKEN_FIELD_NUMBER = 2;
    private volatile java.lang.Object token_;
    /**
     * <code>optional string token = 2;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>optional string token = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISVAILD_FIELD_NUMBER = 3;
    private boolean isVaild_;
    /**
     * <pre>
     *用户token时候有效
     * </pre>
     *
     * <code>optional bool isVaild = 3;</code>
     */
    public boolean getIsVaild() {
      return isVaild_;
    }

    public static final int TRACEID_FIELD_NUMBER = 4;
    private long traceId_;
    /**
     * <pre>
     *记录ID
     * </pre>
     *
     * <code>optional int64 traceId = 4;</code>
     */
    public long getTraceId() {
      return traceId_;
    }

    public static final int EXTRA_FIELD_NUMBER = 5;
    private volatile java.lang.Object extra_;
    /**
     * <pre>
     *用于扩展信息
     * </pre>
     *
     * <code>optional string extra = 5;</code>
     */
    public java.lang.String getExtra() {
      java.lang.Object ref = extra_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        extra_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用于扩展信息
     * </pre>
     *
     * <code>optional string extra = 5;</code>
     */
    public com.google.protobuf.ByteString
        getExtraBytes() {
      java.lang.Object ref = extra_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extra_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISMSGBLOCKED_FIELD_NUMBER = 6;
    private boolean isMsgBlocked_;
    /**
     * <pre>
     *是否开启消息免打扰
     * </pre>
     *
     * <code>optional bool isMsgBlocked = 6;</code>
     */
    public boolean getIsMsgBlocked() {
      return isMsgBlocked_;
    }

    public static final int PUSHCOUNT_FIELD_NUMBER = 7;
    private long pushCount_;
    /**
     * <pre>
     *push计数
     * </pre>
     *
     * <code>optional int64 pushCount = 7;</code>
     */
    public long getPushCount() {
      return pushCount_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
      }
      if (isVaild_ != false) {
        output.writeBool(3, isVaild_);
      }
      if (traceId_ != 0L) {
        output.writeInt64(4, traceId_);
      }
      if (!getExtraBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, extra_);
      }
      if (isMsgBlocked_ != false) {
        output.writeBool(6, isMsgBlocked_);
      }
      if (pushCount_ != 0L) {
        output.writeInt64(7, pushCount_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
      }
      if (isVaild_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isVaild_);
      }
      if (traceId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, traceId_);
      }
      if (!getExtraBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, extra_);
      }
      if (isMsgBlocked_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, isMsgBlocked_);
      }
      if (pushCount_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, pushCount_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser)) {
        return super.equals(obj);
      }
      com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser other = (com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser) obj;

      boolean result = true;
      result = result && (getSuccess()
          == other.getSuccess());
      result = result && getToken()
          .equals(other.getToken());
      result = result && (getIsVaild()
          == other.getIsVaild());
      result = result && (getTraceId()
          == other.getTraceId());
      result = result && getExtra()
          .equals(other.getExtra());
      result = result && (getIsMsgBlocked()
          == other.getIsMsgBlocked());
      result = result && (getPushCount()
          == other.getPushCount());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + ISVAILD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsVaild());
      hash = (37 * hash) + TRACEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTraceId());
      hash = (37 * hash) + EXTRA_FIELD_NUMBER;
      hash = (53 * hash) + getExtra().hashCode();
      hash = (37 * hash) + ISMSGBLOCKED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsMsgBlocked());
      hash = (37 * hash) + PUSHCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPushCount());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.gomeplus.grpc.protobuf.ResponseUser}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.gomeplus.grpc.protobuf.ResponseUser)
        com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gomeplus.grpc.protobuf.UserRpcServices.internal_static_com_gomeplus_grpc_protobuf_ResponseUser_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gomeplus.grpc.protobuf.UserRpcServices.internal_static_com_gomeplus_grpc_protobuf_ResponseUser_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser.class, com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser.Builder.class);
      }

      // Construct using com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        success_ = false;

        token_ = "";

        isVaild_ = false;

        traceId_ = 0L;

        extra_ = "";

        isMsgBlocked_ = false;

        pushCount_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gomeplus.grpc.protobuf.UserRpcServices.internal_static_com_gomeplus_grpc_protobuf_ResponseUser_descriptor;
      }

      public com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser getDefaultInstanceForType() {
        return com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser.getDefaultInstance();
      }

      public com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser build() {
        com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser buildPartial() {
        com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser result = new com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser(this);
        result.success_ = success_;
        result.token_ = token_;
        result.isVaild_ = isVaild_;
        result.traceId_ = traceId_;
        result.extra_ = extra_;
        result.isMsgBlocked_ = isMsgBlocked_;
        result.pushCount_ = pushCount_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser) {
          return mergeFrom((com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser other) {
        if (other == com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (other.getIsVaild() != false) {
          setIsVaild(other.getIsVaild());
        }
        if (other.getTraceId() != 0L) {
          setTraceId(other.getTraceId());
        }
        if (!other.getExtra().isEmpty()) {
          extra_ = other.extra_;
          onChanged();
        }
        if (other.getIsMsgBlocked() != false) {
          setIsMsgBlocked(other.getIsMsgBlocked());
        }
        if (other.getPushCount() != 0L) {
          setPushCount(other.getPushCount());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean success_ ;
      /**
       * <code>optional bool success = 1;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>optional bool success = 1;</code>
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool success = 1;</code>
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>optional string token = 2;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string token = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string token = 2;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 2;</code>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 2;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }

      private boolean isVaild_ ;
      /**
       * <pre>
       *用户token时候有效
       * </pre>
       *
       * <code>optional bool isVaild = 3;</code>
       */
      public boolean getIsVaild() {
        return isVaild_;
      }
      /**
       * <pre>
       *用户token时候有效
       * </pre>
       *
       * <code>optional bool isVaild = 3;</code>
       */
      public Builder setIsVaild(boolean value) {
        
        isVaild_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户token时候有效
       * </pre>
       *
       * <code>optional bool isVaild = 3;</code>
       */
      public Builder clearIsVaild() {
        
        isVaild_ = false;
        onChanged();
        return this;
      }

      private long traceId_ ;
      /**
       * <pre>
       *记录ID
       * </pre>
       *
       * <code>optional int64 traceId = 4;</code>
       */
      public long getTraceId() {
        return traceId_;
      }
      /**
       * <pre>
       *记录ID
       * </pre>
       *
       * <code>optional int64 traceId = 4;</code>
       */
      public Builder setTraceId(long value) {
        
        traceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *记录ID
       * </pre>
       *
       * <code>optional int64 traceId = 4;</code>
       */
      public Builder clearTraceId() {
        
        traceId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object extra_ = "";
      /**
       * <pre>
       *用于扩展信息
       * </pre>
       *
       * <code>optional string extra = 5;</code>
       */
      public java.lang.String getExtra() {
        java.lang.Object ref = extra_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          extra_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用于扩展信息
       * </pre>
       *
       * <code>optional string extra = 5;</code>
       */
      public com.google.protobuf.ByteString
          getExtraBytes() {
        java.lang.Object ref = extra_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          extra_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用于扩展信息
       * </pre>
       *
       * <code>optional string extra = 5;</code>
       */
      public Builder setExtra(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        extra_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用于扩展信息
       * </pre>
       *
       * <code>optional string extra = 5;</code>
       */
      public Builder clearExtra() {
        
        extra_ = getDefaultInstance().getExtra();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用于扩展信息
       * </pre>
       *
       * <code>optional string extra = 5;</code>
       */
      public Builder setExtraBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        extra_ = value;
        onChanged();
        return this;
      }

      private boolean isMsgBlocked_ ;
      /**
       * <pre>
       *是否开启消息免打扰
       * </pre>
       *
       * <code>optional bool isMsgBlocked = 6;</code>
       */
      public boolean getIsMsgBlocked() {
        return isMsgBlocked_;
      }
      /**
       * <pre>
       *是否开启消息免打扰
       * </pre>
       *
       * <code>optional bool isMsgBlocked = 6;</code>
       */
      public Builder setIsMsgBlocked(boolean value) {
        
        isMsgBlocked_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否开启消息免打扰
       * </pre>
       *
       * <code>optional bool isMsgBlocked = 6;</code>
       */
      public Builder clearIsMsgBlocked() {
        
        isMsgBlocked_ = false;
        onChanged();
        return this;
      }

      private long pushCount_ ;
      /**
       * <pre>
       *push计数
       * </pre>
       *
       * <code>optional int64 pushCount = 7;</code>
       */
      public long getPushCount() {
        return pushCount_;
      }
      /**
       * <pre>
       *push计数
       * </pre>
       *
       * <code>optional int64 pushCount = 7;</code>
       */
      public Builder setPushCount(long value) {
        
        pushCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *push计数
       * </pre>
       *
       * <code>optional int64 pushCount = 7;</code>
       */
      public Builder clearPushCount() {
        
        pushCount_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.gomeplus.grpc.protobuf.ResponseUser)
    }

    // @@protoc_insertion_point(class_scope:com.gomeplus.grpc.protobuf.ResponseUser)
    private static final com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser();
    }

    public static com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseUser>
        PARSER = new com.google.protobuf.AbstractParser<ResponseUser>() {
      public ResponseUser parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ResponseUser(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseUser> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseUser> getParserForType() {
      return PARSER;
    }

    public com.gomeplus.grpc.protobuf.UserRpcServices.ResponseUser getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gomeplus_grpc_protobuf_RequestUser_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gomeplus_grpc_protobuf_RequestUser_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gomeplus_grpc_protobuf_ResponseUser_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gomeplus_grpc_protobuf_ResponseUser_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025UserRpcServices.proto\022\032com.gomeplus.gr" +
      "pc.protobuf\"\225\001\n\013RequestUser\022\r\n\005appId\030\001 \001" +
      "(\t\022\016\n\006userId\030\002 \001(\003\022\r\n\005token\030\003 \001(\t\022\017\n\007tra" +
      "ceId\030\004 \001(\003\022\r\n\005extra\030\005 \001(\t\022\022\n\nclientType\030" +
      "\006 \001(\005\022\017\n\007groupId\030\007 \001(\t\022\023\n\013manufacture\030\010 " +
      "\001(\005\"\210\001\n\014ResponseUser\022\017\n\007success\030\001 \001(\010\022\r\n" +
      "\005token\030\002 \001(\t\022\017\n\007isVaild\030\003 \001(\010\022\017\n\007traceId" +
      "\030\004 \001(\003\022\r\n\005extra\030\005 \001(\t\022\024\n\014isMsgBlocked\030\006 " +
      "\001(\010\022\021\n\tpushCount\030\007 \001(\0032\305\005\n\013UserService\022]" +
      "\n\010getToken\022\'.com.gomeplus.grpc.protobuf.",
      "RequestUser\032(.com.gomeplus.grpc.protobuf" +
      ".ResponseUser\022c\n\016checkUserToken\022\'.com.go" +
      "meplus.grpc.protobuf.RequestUser\032(.com.g" +
      "omeplus.grpc.protobuf.ResponseUser\022a\n\014ge" +
      "tPushToken\022\'.com.gomeplus.grpc.protobuf." +
      "RequestUser\032(.com.gomeplus.grpc.protobuf" +
      ".ResponseUser\022a\n\014setPushToken\022\'.com.gome" +
      "plus.grpc.protobuf.RequestUser\032(.com.gom" +
      "eplus.grpc.protobuf.ResponseUser\022d\n\017getI" +
      "sMsgBlocked\022\'.com.gomeplus.grpc.protobuf",
      ".RequestUser\032(.com.gomeplus.grpc.protobu" +
      "f.ResponseUser\022a\n\014incPushCount\022\'.com.gom" +
      "eplus.grpc.protobuf.RequestUser\032(.com.go" +
      "meplus.grpc.protobuf.ResponseUser\022c\n\016cle" +
      "anPushCount\022\'.com.gomeplus.grpc.protobuf" +
      ".RequestUser\032(.com.gomeplus.grpc.protobu" +
      "f.ResponseUserB\002P\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_gomeplus_grpc_protobuf_RequestUser_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_gomeplus_grpc_protobuf_RequestUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gomeplus_grpc_protobuf_RequestUser_descriptor,
        new java.lang.String[] { "AppId", "UserId", "Token", "TraceId", "Extra", "ClientType", "GroupId", "Manufacture", });
    internal_static_com_gomeplus_grpc_protobuf_ResponseUser_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_gomeplus_grpc_protobuf_ResponseUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gomeplus_grpc_protobuf_ResponseUser_descriptor,
        new java.lang.String[] { "Success", "Token", "IsVaild", "TraceId", "Extra", "IsMsgBlocked", "PushCount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
